services:
  database:
    image: mysql:8.0.33
    container_name: book-eye-test-mysql
    restart: always
    environment:
      TZ: Asia/Tokyo
      MYSQL_DATABASE: book_eye
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./mysql/volumes/my.cnf:/etc/mysql/conf.d/my.cnf
      - ../sql:/docker-entrypoint-initdb.d
    ports:
      - 63306:3306
