app:
  api:
    password:
      bcrypt-strength: ${PASSWORD_STRENGTH}
  gateway:
    env:
      system-setting:
        access-key: ${SYSTEM_ACCESS_KEY:}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_eye
    username: root
    password: test

logging:
  level:
    root: ${WEB_LOGGING_LEVEL:INFO}
    org.springframework: INFO
