on:
	workflow_dispatch:
	push:
		paths:
		 - server/**
			
jobs:
	test:
		runs-on: ubuntu-latest
		defaults:
			run:
				working-directory: server
				
	steps: 
		- name: Check out
			uses: actions/checkout@v3
			
		- name: Setup Microsoft Open JDK 17
			uses: actions/setup-java@v3
			with:
				java-version: '17'
				distribution: microsoft
				
		- name: Grant Excecte Permission for Gradle
			run: chmod +x gradlew
		
		- name: Execute Test
			run: ./gradlew test
		
		- name: Excecute Integration Test
			run: ./gradlew integrationTest
